### ISSUE TITLE
question with add_matrix dimensions

### ISSUE THREAD

**Issue by opasquetdotfr** [gesellkammer/pysdif3#3]
Hello!

First, thank you for the work...!!!

I am using _add_matrix_ within a loop to iterate onsets.
I saw somewhere that _add_matrix_ was taking a 2d matrix. But I only need a 1d matrix.

Here is my code:
```
for i, tui in enumerate(times):
	with sdifile.new_frame('1PSO', tui) as frame:
		frame.add_matrix('ITDS', np.array([float(sr)]))
		frame.add_matrix('1PSO', np.array([pitches[i], harmonic_rates[i], argmins[i], 0., 0., 0., 0., 0.]))
sdifile.close()
```

The outcome is a 8x1 matrix:
```
SDFC

1PSO	2	0	0
  ITDS	0x0008	1	1
	48000
  1PSO	0x0008	8	1
	200
	0.682259
	0
	0
	0
	0
	0
	0
```

I should have a 1x8 matrix like the following. How should I do?:

```
SDFC

1PSO	2	0	0.0104375
  ITDS	0x0004	1	1
	48000
  1PSO	0x0004	1	8
	501	80.4742	0	0.296868	35.1562	501	-0.126867	0
```

Does it matter?

Thank you very much for your help!!!

O.

**Comment by gesellkammer** [comment]
Can you post the complete code, to test it?

**Comment by opasquetdotfr** [comment]
Hello!

Yes! Thank you for your prompt answer!!
I am actually redoing the good old "psola_analysis" from yin.

Same question: _new_frame_one_matrix_ gives a 2d matrix even though I feed it with a 1d matrix:

```
	if audioDir is not None:
		audioFilePath = audioDir + sep + audioFileName
	else:
		audioFilePath = audioFileName

	sr, sig = audio_read(audioFilePath, formatsox=False)

	start = time.time()
	pitches, harmonic_rates, argmins, times = compute_yin(sig, sr, dataFileName, w_len, w_step, f0_min, f0_max, harmo_thresh)
	end = time.time()

	sdifile = SdifFile("3_test.1PSO.sdif", "w")
	sdifile.add_NVT({"creator": "Olive"})
	sdifile.add_NVT({"Force_fcmax": "No", "MarkBeta": "0.050000", "MarkGamma": "5.000000", "VoiceThreshold": "0.600000", "TransThreshold": "0.200000", "MarkAlpha": "4.000000", "External_f0": "No", "f0_fmin": "50.000000", "f0_fmax": "1000.000000", "MethodEpocs": "ener", "LpcOrder": "None"})
	sdifile.add_matrix_type('ITDS',"SamplingRate")
	sdifile.add_matrix_type('1PSO',"Position, Fundamentalfrequency, VoicingFlag, VoicingCoefficient, VoicingCuttingFrequency, Periods, Mod, TransitoireFlag")
	sdifile.add_frame_type("1PSO", ["1PSO PSOLA"])

	for i, tui in enumerate(times):
		sdifile.new_frame_one_matrix("1PSO", tui, "ITDS", np.array([float(sr)]))
		sdifile.new_frame_one_matrix('1PSO', tui, "1PSO", np.array([pitches[i], harmonic_rates[i], argmins[i], 0., 0., 0., 0., 0.]))
	sdifile.close()
```

Here is the kind of SDIF files I am trying to build (converted into txt):
[3.1PSO.sdif.txt](https://github.com/gesellkammer/pysdif3/files/13943817/3.1PSO.sdif.txt)
[3.1PSO.sdif.zip](https://github.com/gesellkammer/pysdif3/files/13943824/3.1PSO.sdif.zip)

**Comment by gesellkammer** [comment]
At the moment, and as indicated in the documentation,new_frame_one_matrix expects a 2D array. This is not ensured and results in an error when passed a 1D array (which is the case for both matrices added in your example). Using new_frame and then add_matrix solves the problem. 
I can see if it is possible to add support for 1D matrices for new_frame_one_matrix for the next release. At least a check to throw an error if given an array with the wrong dimensions.

**Comment by opasquetdotfr** [comment]
Thank you very much!!

I do this:
```
	for i, tui in enumerate(times):
		with sdifile.new_frame("1PSO", tui) as outframe:
			outframe.add_matrix("ITDS", np.array([float(sr)]))
			outframe.add_matrix("1PSO", np.array([pitches[i], harmonic_rates[i], argmins[i], 0., 0., 0., 0., 0.]))
```

and I still get a vertical array, instead of horizontal.
Something like this; the left side is what I am after; the right one is what I get:

<img width="817" alt="Screenshot 2024-01-16 at 01 28 12" src="https://github.com/gesellkammer/pysdif3/assets/11800455/8fbd03e2-976e-467c-8521-eb0f4890a269">

I am converting the SDIF file to text using SDIFToText from Ircam ~2007-2014. This could be found from the [Audiosculpt](http://anasynth.ircam.fr/home/english/software/audiosculpt) release (which is now over).

**Comment by gesellkammer** [comment]
Your expectations about the shape are wrong. In SDIF a matrix is defined as a series of rows with a number of given columns, so in principle all matrices are 2D. When you define a matrix, you define how many columns it will have. In your case it will have one column. Since you are passing a 1D array, it is interpreted as having the shape (len(array), 1). If it were the other way around it would be interpreted as being a row with 8 columns, which does not coincide with the definition of the matrix type.

**Comment by opasquetdotfr** [comment]
Answer: A matrix from an Ircam SDIFToText file shown "horizontally" or "vertically" does not change anything to the actual dimensions.
I simply made it work afterward.
